name: Go

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'
        
    - name: Build
      run: go build -o cloudblocks
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role-2
        
    - name: Upload to S3
      run: aws s3 cp cloudblocks s3://cloudblocks-binaries/cli/cloudblocks
      
    - name: Verify the file in S3
      run: |
        if aws s3 ls s3://cloudblocks-binaries/cloudblocks; then
          echo "Binary uploaded successfully to S3"
        else
          echo "Binary not found in S3"
          exit 1
        fi
